name: Slack Notification
on:
  schedule:
   - cron: '30 14 * * *' # 2:30 pm UTC == 8:00 pm IST
  workflow_dispatch:
    inputs:
      region:
        description: 'AWS Region'
        required: true
        default: 'ap-northeast-1'
jobs:
  push-to-slack:
    runs-on: ubuntu-latest
    name: Notification
    steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-node@v2
          with:
            node-version: '18'
        - run: |
            npm install
            npm set audit false
            chmod u+x slack.js
            ./slack.js --secret-key ${{ secrets.SECRET_KEY }} --access-key ${{ secrets.ACCESS_KEY }} --region ${{ github.event.inputs.region }} --slack-webhook ${{ secrets.SLACK_WEBHOOK }}